### ISSUE TITLE
Demo app crashes on startup in iOS

### ISSUE THREAD

**Issue by lattice-it** [davecoffin/nativescript-blur#1]
Hi

Demo app is crashing on iOS during the startup.

### Which platform(s) does your issue occur on?
- iOS
- Verified it on iOS 10.3 and 11.0 
- emulator.

### Please, provide the following version numbers that your issue occurs with:

- CLI: 3.2.1

**Comment by davecoffin** [comment]
Can you provide more details? What version of Nativescript, what version of ios platforms are you on, is there an error message?

**Comment by lattice-it** [comment]
Nativescript - 3.2.1
It crashed on iOS 11.0 and 10.3 simulators.
Error message
Error: Could not find module 'nativescript-blur'. Computed path '~/Library/Developer/CoreSimulator/Devices/E3390E4B-93BA-4A40-A248-7F3D2E1F5607/data/Containers/Bundle/Application/0AEC99A5-08A7-4A17-A43C-36CA473978C0/demo.app/app/tns_modules/nativescript-blur'.

There is a symlink from demo/node_modules to ../src folder for blur

**Comment by lattice-it** [comment]
It works if I change the blur dependency to
"nativescript-blur": "1.0.9",

**Comment by davecoffin** [comment]
Yup, indeed 1.0.9 is the latest release.
